# Generated by Django 4.1.2 on 2023-03-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_recommand_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
