# Generated by Django 4.1.7 on 2023-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_recommand_app", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Account",),
        migrations.RemoveField(model_name="profile", name="location",),
        migrations.RemoveField(model_name="profile", name="role",),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
