# Generated by Django 4.2 on 2023-04-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommand_app', '0004_delete_account_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keyword',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
